### ISSUE TITLE
removeSquircle() function?

### ISSUE THREAD

**Issue by claesjacobsson** [AlphaSheeps/Squircle#17]
**Is your feature request related to a problem? Please describe.**
If we're reusing a view, for example in a table view cell, perhaps we'd like to be able to remove the squircle as easily as we can add one?

**Describe the solution you'd like**
I'd like to be able to call view.removeSquircle()

**Comment by claesjacobsson** [comment]
I already took a stab at this. Saw now that you self-assigned it. Would like to take a look at my PR anyway?

Regarding the current version number I'm a bit confused. Is it 2.1.0? Has the podspec been updated?

**Comment by neobeppe** [comment]
2.1.0 is already released with squircle with borders.
Sure, I'll look to your PR!

**Comment by claesjacobsson** [comment]
I'm probably missing something, but looking at the podspec it says 2.0.0.

https://github.com/neobeppe/Squircle/blob/master/Squircle.podspec

**Comment by neobeppe** [comment]
Got some problem with local branches, now it's updated
