### ISSUE TITLE
Overlapping same sized squircles showing not covering each other completely

### ISSUE THREAD

**Issue by atulkhatri** [AlphaSheeps/Squircle#22]
**Describe the bug**
• Create 2 squircles with the same size. 
• Add them one on top of the other in parent view
• Observe the top squircle is not covering the bottom squircle fully and some border of the bottom one still showing up.

**To Reproduce**
1. Create 2 squircle shapes with 40x40 size in ViewController
2. Assign Squircle1 Black background and add it on a specific Origin i.e. (0, 0)
3. Assign Squircle2 White background and add it on the same origin as the Squircle1 i.e. (0, 0)
4. Observe that Squircle1 showing up a little from all corners even though Squircle2 is overlapping it.

Image: https://pasteboard.co/61nMXUcvUGFj.png

**Expected behavior**
Bottom Squircle shouldn't be showing up and Squircle2 should be completely covering it.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Simulator
 - OS: iOS 16.4 Simulator

**Additional context**
N/A

**Comment by neobeppe** [comment]
This is an iOS glitch. After checking, the drawn curve is exactly the same for both views, but the renderer shows a small edge. It is not fixable.
